config/routes.rb
Spoutlets::Application.routes.draw do
  devise_for :users
  devise_for :therapists, controllers: {
    omniauth_callbacks: "therapists/omniauth_callbacks",
    invitations: "therapists/invitations"}

  devise_scope :user do
    get 'signin', to: 'devise/sessions#new', as: :signin
    get 'signout', to:  'devise/sessions#destroy', as: :signout
  end

  resources :users
  get 'signup', to: "users#new", as: :signup

  resources :therapists

  devise_scope :therapist do
    delete 'signout', to:  'devise/sessions#destroy', as: :therapist_signout
  end

  resources :entries do
    put :like, on: :member
    put :unlike, on: :member
  end

  root to: 'home#index'
end

app/models/entry.rb
class Entry
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Likeable

  field :title,            type: String
  field :content,          type: String
  field :happiness_level,  type: Integer
  field :anxiety_level,    type: Integer
  field :irritation_level, type: Integer
  field :category,         type: String
  field :published,        type: Boolean

  belongs_to :user

  validates :content, presence: true
  validates :category, presence: true

  # Syntactic sugar for class method
  # def self.recent(3)
  #   desc(:created_at).limit(3)
  # end
  scope :latest, desc(:created_at).limit(3)

  def self.mood_chart
    LazyHighCharts::HighChart.new('pie') do |chart|
      chart.options[:chart][:defaultSeriesType] = "pie"
      chart.options[:chart][:height] = 210
      chart.options[:title][:text] = "Issues on everybody's mind"
      chart.options[:chart][:backgroundColor] = '#f5f0d7'
      chart.series({
                     name: 'Total',
                     data: fetch_categories
                   })
    end
  end

  def self.fetch_categories
    categories = all.map do |entry|
      entry.category
    end

    {}.tap do |h|
      categories.each do |category|
        h[category] ||= 0
        h[category] += 1
      end
    end.to_a
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :index]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.where(published: true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  def like
    @entry = Entry.find(params[:id])
    respond_to do |format|
      format.html do
        if current_user
          @entry.like current_user
          redirect_to entries_url
        else
          redirect_to root_url, notice: "You need to sign in to like an entry."
        end
      end
      format.js
    end
  end

  def unlike
    @entry = Entry.find(params[:id])
    respond_to do | format |
      format.html do
        @entry.unlike current_user
        redirect_to entries_url
      end
      format.js
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])
    @entry.user = current_user

    respond_to do |format|
      if @entry.save
        format.html { redirect_to user_url(current_user), notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])
    @entry.user = current_user

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to user_url(current_user), notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to user_url(current_user), notice: 'Entry was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper

  def width_for(emotional_state)
    emotional_state.to_i * 20
  end

  def like_status_for(entry, user)
    return "No one else knows the feeling." if entry.likes == 0
    out = []
    if entry.likes == 1
      if entry.liked?(user)
        out << "You know"
      else
        out << "Another person knows"
      end
    else#likes > 1
      if entry.liked?(user)
        likes = entry.likes - 1
        out << "You and"
      else
        likes = entry.likes
      end
      out << "<b>#{likes}</b> others know"
    end
    out << "the feeling."
    out.join(" ").html_safe
  end

  def like_button_for(entry, user)
    unless user == entry.user
      if entry.liked?(user)
        like_or_unlike_action = unlike_entry_path(entry)
        css_class = "active"
        title = " un-been there"
      else
        like_or_unlike_action = like_entry_path(entry)
        css_class = ""
        title = " been there"
      end
      return link_to(content_tag(:i, nil, class: "icon-heart") + title, like_or_unlike_action, method: :put, remote: true, class: "btn btn-mini btn-inverse pull-right #{css_class}")
    end
  end
end

app/views/entries/_form.html.erb
<%= simple_form_for(@entry) do |f| %>
<%= f.error_notification %>
<div class="row">
  <div class="span7">
    <%= f.input :title, wrapper: :prepend, label: false do %>
      <%= content_tag :span, "Title", class: "add-on" %>
      <%= f.input_field :title, class: "span6" %>
    <% end %>
  </div>
  <div class="span4">
    <%= f.input :published,
        as: :boolean,
        label: "Share with community",
        input_html: { data: {toggle: :checkbox} } %>
  </div>
</div>
<div class="row">
  <div class="span7">
    <%= f.input :content,
        as: :text,
        label: false,
        placeholder: "Give more details about what you're dealing with",
        input_html: { rows: 7, class: "span7" } %>
  </div>
</div>

<div class="row">
  <div class="span7">
    <div class="well">
      <div class="row">
        <div class="span2">
          <%= f.input :happiness_level,
              input_html: {
                class: "span2 slider",
                :"data-slider-value" => @entry.happiness_level } %>
        </div>
        <div class="span2">
          <%= f.input :anxiety_level,
              input_html: {
                class: "span2 slider",
                :"data-slider-value" => @entry.anxiety_level } %>
        </div>
        <div class="span2">
          <%= f.input :irritation_level,
              input_html: {
                class: "span2 slider",
                :"data-slider-value" => @entry.irritation_level } %>
        </div>
      </div>
      <div class="row">
        <div class="span7">
          <%= f.input :category,
              collection: [
                ["other"],
                ["just feeling off"],
                ["alcohol/drugs"],
                ["body/health"],
                ["dreams/sleep"],
                ["family/friends"],
                ["sex/relationships"],
                ["work/school"],
              ],
              label: "Categorize your entry to understand what bothers or delights you regularly" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12">
    <%= f.button :submit, "Log it!",
        class: "btn-large btn-block btn-primary" %>
  </div>
</div>
<% end %>

app/views/entries/edit.html.erb
<h4>Editing entry</h4>
<hr />
<%= render 'form' %>

app/views/entries/index.html.erb
<div class="row">
  <div class="span5 offset3">
    <%= high_chart("chart_id", @entries.mood_chart) do |c|%>
       <%= "options.colors = #{chart_colors}".html_safe %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span12">
    <h3>
      Shared entries
    </h3>
    <ul class="nav nav-list">
      <li class="divider"></li>
    </ul>
  </div>
</div>

<!-- Entry -->
<% @entries.reverse.each do |entry| %>
<div class="row">
  <div class="span7">
    <h4>
      <%= entry.title %>
    </h4>
  </div>
</div>

<div class="row">
  <div class="span8">
    <p>
      <%= simple_format(entry.content) %>
    </p>
    <span data-toggle="tooltip" data-placement="right" title="Shared with community">
      <i class="icon-unlock"></i><small> by </small><i class="icon-user"> </i><small> anonymous on </small><i class="icon-calendar"> </i><small> <%= entry.created_at.to_date.strftime('%a %b %d, %Y') %> under</small>
      <span class="label label-inverse"><%= entry.category %></span>
    </span>
  </div>
  <div class="span3 offset1">
    <span class="pull-right">
      <div class="like_status" id="entry_status_<%= entry.id %>">
        <%= like_status_for(entry, current_user) %>
      </div>
      <div id="entry_message_<%= entry.id %>"></div>
    </span>
    <br /><br />
    <div class="like_action" id="entry_like_<%= entry.id %>"><%= like_button_for(entry, current_user) %></div>
    <br /><br /><br />
    <% if entry.happiness_level && entry.happiness_level > 0 %>
    <p class="text-success">happiness</p>
    <div class="progress">
      <div class="bar bar-success" style="width: <%= width_for(entry.happiness_level) %>%;"></div>
    </div>
    <% end %>

    <% if entry.anxiety_level && entry.anxiety_level > 0 %>
    <p class="text-warning">anxiety</p>
    <div class="progress">
      <div class="bar bar-warning" style="width: <%= width_for(entry.anxiety_level) %>%;"></div>
    </div>
    <% end %>

    <% if entry.irritation_level && entry.irritation_level > 0 %>
    <p class="text-danger">irritation</p>
    <div class="progress">
      <div class="bar bar-danger" style="width: <%= width_for(entry.irritation_level) %>%;"></div>
    </div>
    <% end %>
  </div>
</div>
<br />
<br />
<div class="row">
  <div class="span12">
    <ul class="nav nav-list">
      <li class="divider"></li>
    </ul>
  </div>
</div>
<% end %><!-- end of Entry -->

app/views/entries/like.js.erb
<% if current_user %>
  <% @entry.like current_user %>
  $("#entry_status_<%= @entry.id %>").html("<%= j(like_status_for(@entry, current_user)) %>");
  $("#entry_like_<%= @entry.id %>").html("<%= j(like_button_for(@entry, current_user)) %>")
<% else %>
  $("#entry_message_<%= @entry.id %>").html("<%= j content_tag(:div, ('You need to ' + link_to('sign in', signin_path) + ' to like an entry.').html_safe, class: 'alert') %>");
<% end -%>

app/views/entries/new.html.erb
<h4><%= Date.today.strftime('%a %b %d, %Y') %></h4>
<hr />
<%= render 'form' %>
<hr />
<div class="row">
  <div class="span12">
    <!-- Entry -->
    <% @entries.reverse.each do |entry| %>
    <div class="well">
      <div class="row">
        <div class="span1">
          <span class="label"><%= entry.category %></span>
        </div>
        <div class="span6 offset1">
          <br />
          <p><small><%= entry.content %></small></p>
          <ul class="nav nav-list">
            <li class="divider"></li>
          </ul>
        </div>
        <div class="span2 offset1">
          <span class="badge badge-info">14</span><br />
          <span class="text-info"> been there</span>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <span class="muted"><small><%= entry.created_at.to_date.strftime('%a %b %d, %Y') %></small></span>
        </div>
        <div class="span2">
          <p class="muted"><small>happiness</small></p>
          <div class="progress">
            <div class="bar" style="width: <%= width_for(entry.happiness_level) %>%;"></div>
          </div>
        </div>
        <div class="span2">
          <p class="muted"><small>anxiety</small></p>
          <div class="progress">
            <div class="bar" style="width: <%= width_for(entry.anxiety_level) %>%;"></div>
          </div>
        </div>
        <div class="span2">
          <p class="muted"><small>irritation</small></p>
          <div class="progress">
            <div class="bar" style="width: <%= width_for(entry.irritation_level) %>%;"></div>
          </div>
        </div>
        <div class="span2 offset1">
          <div class="btn-toolbar">
            <div class="btn-group">
              <%= link_to raw('<i class="icon-edit"></i>'),
              edit_entry_path(entry), class: "btn" %>

              <%= link_to raw('<i class="icon-trash"></i>'), entry,
              method: :delete, data: { confirm: "Are you sure?" },
              class: "btn" %>
            </div>
          </div>
        </div>
      </div>
    </div><!-- end of well -->
    <% end %><!-- end of Entry -->
  </div><!-- end of span12 -->
</div>

app/views/entries/preview.html.erb
<h4>This is a preview of your entry.</h4>

<p>
  <b>Title:</b>
  <%= @entry.title %>
</p>
<p>
  <b>Content:</b>
  <%= @entry.content %>
</p>
<p>
  <b>Happiness level:</b>
  <%= @entry.happiness_level %>
</p>
<p>
  <b>Anxiety level:</b>
  <%= @entry.anxiety_level %>
</p>
<p>
  <b>Irritation level:</b>
  <%= @entry.irritation_level %>
</p>
<p>
  <b>Category:</b>
  <%= @entry.category %>
</p>
<p>
  <b>Public:</b>
  <%= @entry.published %>
</p>

<% if user_signed_in? %>
  <%= form_for @entry do |f| %>
    <%= f.hidden_field :approved, value: true %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Approve this entry", class: "btn btn-block btn-success" %>
  <% end %>
<% else %>
  <div class="well">
    <p>In order to log this entry you need to sign in. You can abandon the entry submission by clicking the 'Cancel this entry' button.</p>
  </div>

  <%= link_to "Sign in with Facebook to confirm this entry", signin_path, class: "btn btn-block btn-success" %>
  <%= link_to "Cancel this entry", @entry, data: {confirm: "Are you sure ?"}, method: :delete, class: "btn btn-block btn-danger" %>
<% end %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @entry.title %>
</p>
<p>
  <b>Content:</b>
  <%= @entry.content %>
</p>
<p>
  <b>Happiness level:</b>
  <%= @entry.happiness_level %>
</p>
<p>
  <b>Anxiety level:</b>
  <%= @entry.anxiety_level %>
</p>
<p>
  <b>Irritation level:</b>
  <%= @entry.irritation_level %>
</p>
<p>
  <b>Category:</b>
  <%= @entry.category %>
</p>
<p>
  <b>Public:</b>
  <%= @entry.published %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/entries/unlike.js.erb
<% @entry.unlike current_user %>
$("#entry_status_<%= @entry.id %>").html("<%= j(like_status_for(@entry, current_user)) %>");
$("#entry_like_<%= @entry.id %>").html("<%= j(like_button_for(@entry, current_user)) %>")