config/routes.rb
Spoutlets::Application.routes.draw do
  devise_for :users
  devise_for :therapists, controllers: {
    omniauth_callbacks: "therapists/omniauth_callbacks",
    invitations: "therapists/invitations"}

  devise_scope :user do
    get 'signin', to: 'devise/sessions#new', as: :signin
    get 'signout', to:  'devise/sessions#destroy', as: :signout
  end

  resources :users
  get 'signup', to: "users#new", as: :signup

  resources :therapists

  devise_scope :therapist do
    delete 'signout', to:  'devise/sessions#destroy', as: :therapist_signout
  end

  resources :entries do
    put :like, on: :member
    put :unlike, on: :member
  end

  root to: 'home#index'
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include DeviseInvitable::Inviter

  rolify

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :name,               type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  field :invitation_limit,       type: Integer

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  attr_accessible :role_ids, as: :admin
  attr_accessible :email, :password, :password_confirmation

  has_one :therapist, foreign_key: "invited_by_id"
  has_many :entries
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true, background: true })

  def mood_chart
    LazyHighCharts::HighChart.new('pie') do |chart|
      chart.options[:chart][:defaultSeriesType] = "pie"
      chart.options[:chart][:height] = 210
      chart.options[:title][:text] = 'Issues on your mind'
      chart.options[:chart][:backgroundColor] = '#f5f0d7'
      chart.series({
                     name: 'Total',
                     data: fetch_categories
                   })
    end
  end

  def fetch_categories
    categories = self.entries.map do |entry|
      entry.category
    end

    {}.tap do |h|
      categories.each do |category|
        h[category] ||= 0
        h[category] += 1
      end
    end.to_a
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:new, :create]
  load_and_authorize_resource

  helper_method :devise_mapping, :resource_name, :resource_class

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    generated_password = Devise.friendly_token.first(8)
    user = User.create(email: params[:user][:email], password: generated_password)
    if user.persisted?
      UserMailer.welcome_email(user, generated_password).deliver
      sign_in(:user, user)
      redirect_to entries_path, notice: "Welcome! You have signed up successfully."
    else
      redirect_to signup_path, notice: "You must provide a valid email address to register!"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


  def show
    @user = User.find(params[:id])
    @entries = @user.entries
  end

  private

  def devise_mapping
    Devise.mappings[:user]
  end

  def resource_name
    devise_mapping.name
  end

  def resource_class
    devise_mapping.to
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def issues_chart(chart_type)
# https://github.com/michelson/lazy_high_charts/blob/master/lib/lazy_high_charts/high_chart.rb
# https://github.com/michelson/lazy_high_charts/blob/master/lib/lazy_high_charts/layout_helper.rb
    chart = Chart.new.build_chart(@user, chart_type)
    high_chart(chart.canvas, chart)
  end
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, :required => true, :autofocus => true %>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
    <% end %>

    <%= f.input :password, :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false %>
    <%= f.input :password_confirmation, :required => false %>
    <%= f.input :current_password, :hint => "we need your current password to confirm your changes", :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete %></p>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="span11 offset1">
    <h3>Register for an account</h3>
  </div>
</div>
<div class="row">
  <div class="span3 offset2">
  <%= simple_form_for @user do |f| %>
    <%= f.error_notification %>
    <%= f.input :email,
        required: true,
        autofocus: true,
        input_html: { class: 'input-xlarge' } %>
    <%= f.button :submit, "Create your account",
        class: "btn-primary btn-large pull-right" %>
  <% end %>
  </div>
  <div class="span2">
  <br /><br /><br />
  <h4 class="text-center">or</h4>
  </div>
  <div class="span4">
    <div class="well">
      <%= render "users/shared/links" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="span5 offset3">
    <%= high_chart("chart_id", @user.mood_chart) do |c| %>
       <%= "options.colors = #{chart_colors}".html_safe %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span12">
    <h3>
      Your entries
    </h3>
    <ul class="nav nav-list">
      <li class="divider"></li>
    </ul>
  </div>
</div>

<!-- Entry -->
<% @entries.reverse.each do |entry| %>
<div class="row">
  <div class="span7">
    <h4>
      <%= entry.title %>
    </h4>
  </div>
</div>

<div class="row">
  <div class="span8">
    <p>
      <%= simple_format(entry.content) %>
    </p>
    <% if entry.published? %>
    <span data-toggle="tooltip" data-placement="right" title="Shared with community">
      <i class="icon-unlock"></i><small> on </small><i class="icon-calendar"> </i><small> <%= entry.created_at.to_date.strftime('%a %b %d, %Y') %> under</small>
      <span class="label label-inverse"><%= entry.category %></span>
    </span>
    <% else %>
    <span data-toggle="tooltip" data-placement="right" title="Kept to yourself">
      <i class="icon-lock"></i><small> on </small><i class="icon-calendar"> </i><small> <%= entry.created_at.to_date.strftime('%a %b %d, %Y') %> under</small>
      <span class="label label-inverse"><%= entry.category %></span>
    </span>
    <% end %>
  </div>
  <div class="span3 offset1">
    <span class="pull-right">
      <div class="like_status" id="entry_status_<%= entry.id %>">
        <%= like_status_for(entry, current_user) %>
      </div>
    </span>
    <br /><br />
    <div class="btn-toolbar pull-right">
      <div class="btn-group">
        <%= link_to raw('<i class="icon-edit"></i>'),
              edit_entry_path(entry),
              class: "btn btn-inverse" %>

        <%= link_to raw('<i class="icon-trash"></i>'),
              entry,
              method: :delete, data: { confirm: "Are you sure?" },
              class: "btn btn-inverse" %>
      </div>
    </div>
    <br /><br /><br />
    <% if entry.happiness_level && entry.happiness_level > 0 %>
    <p class="text-success">happiness</p>
    <div class="progress">
      <div class="bar bar-success" style="width: <%= width_for(entry.happiness_level) %>%;"></div>
    </div>
    <% end %>

    <% if entry.anxiety_level && entry.anxiety_level > 0 %>
    <p class="text-warning">anxiety</p>
    <div class="progress">
      <div class="bar bar-warning" style="width: <%= width_for(entry.anxiety_level) %>%;"></div>
    </div>
    <% end %>

    <% if entry.irritation_level && entry.irritation_level > 0 %>
    <p class="text-danger">irritation</p>
    <div class="progress">
      <div class="bar bar-danger" style="width: <%= width_for(entry.irritation_level) %>%;"></div>
    </div>
    <% end %>
  </div>
</div>
<br />
<br />
<div class="row">
  <div class="span12">
    <ul class="nav nav-list">
      <li class="divider"></li>
    </ul>
  </div>
</div>
<% end %><!-- end of Entry -->