config/routes.rb
Spoutlets::Application.routes.draw do
  devise_for :users
  devise_for :therapists, controllers: {
    omniauth_callbacks: "therapists/omniauth_callbacks",
    invitations: "therapists/invitations"}

  devise_scope :user do
    get 'signin', to: 'devise/sessions#new', as: :signin
    get 'signout', to:  'devise/sessions#destroy', as: :signout
  end

  resources :users
  get 'signup', to: "users#new", as: :signup

  resources :therapists

  devise_scope :therapist do
    delete 'signout', to:  'devise/sessions#destroy', as: :therapist_signout
  end

  resources :entries do
    put :like, on: :member
    put :unlike, on: :member
  end

  root to: 'home#index'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="row">
  <div class="span6">
    <%= link_to "Spoutlets", root_path, :class => 'brand' %>
    <br />
    <span class="text-inverse"><small>the <i class="icon-wrench"></i> you need for mental wellness</small></span>
  </div>
  <!-- Right Nav -->
  <div class="span6">
    <ul class="nav pull-right">
    <% if user_signed_in? %>
      <li>
        <%= link_to raw('<i class="icon-group" data-toggle="tooltip" title="Your community" data-placement="bottom"></i>'),
              entries_path %>
      </li>
      <li>
        <%= link_to raw('<i class="icon-book" data-toggle="tooltip" title="Your journal" data-placement="bottom"></i>'),
              current_user %>
      </li>
      <li>
        <%= link_to raw('<i class="icon-share" data-toggle="tooltip" title="Share with therapist" data-placement="bottom"></i>'),
              new_therapist_invitation_path %>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle"
        data-toggle="dropdown"><i class="icon-cog"></i> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">settings</a></li>
          <li class="divider"></li>
          <li><%= link_to 'logout', signout_path %></li>
        </ul>
      </li>
      <%= link_to raw('<i class="icon-plus"></i> log an entry'),
            new_entry_path,
            class: "btn btn-small btn-embossed btn-primary",
            style: "margin-top: 10px;",
            method: :get  %>
    <% else %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle"
        data-toggle="dropdown">register or login<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "for people", signin_path %></li>
          <li class="divider"></li>
          <li><%= link_to "for therapists",  therapist_omniauth_authorize_path(:linkedin)%></li>
        </ul>
      </li>
      <%= link_to raw('<i class="icon-plus"></i> log an entry'),
            new_entry_path,
            class: "btn btn-small btn-embossed btn-primary",
            style: "margin-top: 10px;",
            method: :get  %>
    <% end %>
    </ul>
  </div> <!-- end of Right Nav -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Spoutlets" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Spoutlets" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-inverse navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>